sudo: required
dist: trusty
language: node_js
node_js:
  - '7'
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - yarn lint --type-check
  - yarn test --watch=false
  - yarn build
cache:
  yarn: true
  directories:
    - node_modules
