sudo: required
dist: trusty
language: node_js
node_js:
- '9'
apt:
  sources:
  - google-chrome
  packages:
  - google-chrome-stable
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- yarn lint
- yarn test --watch=false
- yarn build
before_deploy:
- openssl aes-256-cbc -K $encrypted_4f2abea1a2b6_key -iv $encrypted_4f2abea1a2b6_iv
  -in ci/deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
- provider: script
  skip_cleanup: true
  script: scp -r -o StrictHostKeychecking=no dist/* ci@paperify.org:/var/www/paperify.org/html
  on:
    branch: master
    tags: true
cache:
  yarn: true
  directories:
  - node_modules
