sudo: required
dist: trusty
language: node_js
node_js:
- '7'
apt:
  sources:
  - google-chrome
  packages:
  - google-chrome-stable
before_install:
- openssl aes-256-cbc -K $encrypted_4f2abea1a2b6_key -iv $encrypted_4f2abea1a2b6_iv
  -in ci/deploy_rsa.enc -out ci/deploy_rsa -d
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- yarn lint --type-check
- yarn test --watch=false
- yarn build
deploy:
- provider: script
  script: scp -i ci/deploy_rsa -r -o StrictHostKeychecking=no dist/* ci@paperify.org:/var/www/paperify.org/html
  on:
    branch: master
    tags: true
cache:
  yarn: true
  directories:
  - node_modules
